"""Static TROVIS controller and hydronic configuration definitions."""

from .hydronic_systems import (
    BUFFER_TANK_CHARGING_SYSTEM_CODES_BY_MODEL,
    FUNCTIONAL_SENSOR_ROLE_KEYS,
    HYDRONIC_CONFIGURATIONS,
    SUPPORTED_MODELS_BY_SYSTEM_CODE,
    SUPPORTED_SYSTEM_CODES_BY_MODEL,
    UNDOCUMENTED_SYSTEM_CODES,
    ConfigurationDefinition,
    ConfigurationTopology,
    get_configuration_definition,
)
from .trovis_models import (
    COMMON_INDIVIDUAL_SENSOR_VARIANTS,
    COMMON_SENSOR_KEYS,
    MODEL_DEFINITIONS,
    THREE_CIRCUIT_SENSOR_KEYS,
    TROVIS_5573,
    TROVIS_5573_1,
    TROVIS_5573_FAMILY_SENSOR_VARIANTS,
    TROVIS_5575,
    TROVIS_5576,
    TROVIS_5578,
    TROVIS_5578_E,
    TROVIS_5579,
    ControllerModel,
    ModelDefinition,
    SensorVariant,
    get_model_definition,
    get_model_definition_for_reported_model,
    model_candidates_for_reported_model,
    sensor_variant,
)

__all__ = [
    "BUFFER_TANK_CHARGING_SYSTEM_CODES_BY_MODEL",
    "COMMON_INDIVIDUAL_SENSOR_VARIANTS",
    "COMMON_SENSOR_KEYS",
    "FUNCTIONAL_SENSOR_ROLE_KEYS",
    "HYDRONIC_CONFIGURATIONS",
    "MODEL_DEFINITIONS",
    "SUPPORTED_MODELS_BY_SYSTEM_CODE",
    "SUPPORTED_SYSTEM_CODES_BY_MODEL",
    "THREE_CIRCUIT_SENSOR_KEYS",
    "TROVIS_5573",
    "TROVIS_5573_1",
    "TROVIS_5573_FAMILY_SENSOR_VARIANTS",
    "TROVIS_5575",
    "TROVIS_5576",
    "TROVIS_5578",
    "TROVIS_5578_E",
    "TROVIS_5579",
    "UNDOCUMENTED_SYSTEM_CODES",
    "ConfigurationDefinition",
    "ConfigurationTopology",
    "ControllerModel",
    "ModelDefinition",
    "SensorVariant",
    "get_configuration_definition",
    "get_model_definition",
    "get_model_definition_for_reported_model",
    "model_candidates_for_reported_model",
    "sensor_variant",
]
